### ISSUE TITLE
What FFS stands for

### ISSUE THREAD

**Issue by lasalvavida** [pbatard/ffs#1]
> easing up the generation of what intel/EDK calls FFS's (whatever that abbreviation means)

If this was meant to be tongue in cheek, then feel free to ignore.

FFS stands for "Firmware File System" as per the [specification](http://www.uefi.org/sites/default/files/resources/PI_Spec_1_6.pdf). GenFfs creates files to be added to a firmware file system.

**Comment by pbatard** [comment]
> If this was meant to be tongue in cheek, then feel free to ignore.

Of course it was. 😄 

But thanks for clarifying, in case people need it.

For what is worth, my main beef with FFS is that I __personally__ would never use something that abbreviates to "File System" if it's going to be used to represent a bunch of parts that needs to be assembled to create a complete firmware file system. I do understand the reason why they did so (they already had the file system generator, so decided to use it to generate modules as file system "pods" for reprocessing), but I think the end result is that it hides a bit too well what the tool ends up being used for in the context of end users of UEFI (who simply want to add modules into existing firmwares) rather than developers of UEFI/EDK2.

Hopefully, people won't read too much into this _fake_ rant about the wisdom of the EDK2, especially considering that I am also an EDK2 contributor...
